### ISSUE TITLE
videos bomb my CPU

### ISSUE THREAD

**Issue by FredericoAndrade** [wikitongues/poly#128]
When interacting with the video feature, some Chrome Helper pushes my processing over 100%, making chrome, and the rest of my computer, impossibly slow.

@bjlaa does this happen with you too?

**Comment by FredericoAndrade** [comment]
Example1 
![video edit bug](https://cloud.githubusercontent.com/assets/2080065/20122797/78a0b362-a5e8-11e6-8db5-2338416fe91e.gif)
:

**Comment by bjlaa** [comment]
Ok, so I got the same issue after a few attempts. It seems that it was caused by the setTimeout handling the replacement of the loader by the iframe. I simply added a condition so that the setTimeout can only be called once. Working well on my side now; let me know if it fixes the issue on your side.
